### ISSUE TITLE
wait_for_proxy_route_available for cluster-proxy addon fails on AKS

### ISSUE THREAD

**Issue by TheRealHaoLiu** [stolostron/ocmplus.cm#85] opened 2022-02-16 18:42 UTC

**Comment by TheRealHaoLiu** [comment] 2022-02-16 20:55
nvm... unable to reproduce... i think it just took longer that time

**Comment by TheRealHaoLiu** [comment] 2022-02-17 20:00
this problem does exist (even tho its just a longer wait) we may need to look into it

**Comment by nathanweatherly** [comment] 2022-03-03 18:52
Complexities:
- Intermittent 
- Might be based on proxy stability
- Might be some stability condition we need to consider for error catching.
- Not sure of root cause

**Comment by hanqiuzh** [comment] 2022-03-22 13:50
Not sure if it's related.
There is an edge case for cluster-proxy that when managedclusteraddon existed, cluster_proxy addon will not wait for managedclusteraddon to be available. 

cluster_proxy is auto-installed to all clusters, so it may hit this edge case easily, and the wait time for that addon installation can be long.

The edge case is now fixed in https://github.com/stolostron/ocmplus.cm/pull/113/files#diff-97963c4e99fa02ad9bde68dddec96b5bc56dc008d665f2666fd558fa0eab9d9b

**Comment by nathanweatherly** [comment] 2022-04-06 15:23
More environmental than actual bug; closing.

**Closed by nathanweatherly** 2022-04-06 15:23 UTC
Labels: bug
